### ISSUE TITLE
Fellows with Family not in San Fran?

### ISSUE THREAD

**Issue by slooker** [codeforamerica/apply#47]
I was just curious if any of the fellows had family that didn't move to San Fran with them and how that worked out?  

I'm interested in applying, but my wife's job isn't one she can relocate with and my son is going into high school with his friends.  That said, I'm very interested in working on something that makes a difference, as right now I do dev work in retail, which doesn't.

**Comment by inaki** [comment]
Hi, 
I am a fellow this year and have been living in SF from December. My son is still in Puerto Rico and I am visiting him in summer. It have been a little bit difficult but times flies here and we do a lot of facetime. My girlfriend was here last year and that was harder, so I think that is more difficult to the people who stayed home. Last year it worked out because we communicate very frequently and using tech like facetime, which make it much more easier. Other thing is that I traveled here few times and she traveled there too. We make it work. So my advice would be that if y'all agree that you should do it, stayed present using technology to share your experiences here and keep update of what is happening there too. Doing traditional mail was very fun too. This is a great experience, you'll really enjoy it.

**Comment by spara** [comment]
I'm a 2013 Fellow and during the fellowship my partner and daughter stayed in Texas. My partner is in politics and she was in the middle of a tough election for the first part of the fellowship, My daughter was shuffled around friends, family and campaign staff during this time. Here's what I learned:

1. This year is about YOU. Your family should agree on this. If your wife wants to start grad school, start a new job or business, they should put it off until you finish the fellowship.

2. Video, email, and text are not a substitute for being there. Schedule regular visits longer than a weekend. Your wife will appreciate the break and sharing the role of primary caretaker will alleviate the resentment.

3. There will be resentment, i.e. you're living the glorious tech startup life, while your family has to deal with things getting to school on time. Being a single parent is a lot of work

4. Your son will miss you because starting high school is traumatic. When my son started high school, we just moved to Maryland and I was in the middle of running a startup. I missed that part of his life, if you are a fellow, try to make sure that you pay extra attention and be prepared to mend fences.

I know that this sounds negative in comparison to the usual 'go for it' advice when it comes to CfA. People who have met me know that I don't candy coat anything. The Fellowship is what you make of it, just know that it comes with a personal cost, especially if you have a family. If you have any questions, I can be reached at sophia@codeforamerica.org.

**Comment by slooker** [comment]
No, I really appreciate it.  These are all really good insights.  It helps
to know the good and the bad.

**Comment by spara** [comment]
I wouldn't say that any of this is bad, they are just choices that have to made. People with families just have to make more choices/decisions. Life is complicated, but the ability to navigate the complications is what makes a good Fellow.

**Comment by slooker** [comment]
I guess "bad" isn't the right term, but it's good to hear the things that were easier and the things that weren't.
